apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "chat_app"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"